### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G9_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by jose-gp21** [comment]
Rede de troca de livros, a ideia consiste em um aplicativo onde as pessoas possam trocar livros usados, promovendo a leitura e a reutilização

**Comment by rafaellucasrockenbach** [comment]
Biblioteca de coisas, a ideia seria uma plataforma onde as pessoas podem emprestar e pegar emprestado itens raramente usados, como ferramentas e equipamentos etc.

**Comment by jdecarli6** [comment]
minha ideia é a gente fazer um Banco de Tempo, basicamente: 

Um sistema onde as pessoas trocam tempo e habilidades em vez de dinheiro. Um exemplo: uma hora de aula de inglês por um concertos de bicicleta

**Comment by RuanW01** [comment]
Pagina web sobre o nicho de moda, será plataforma social de moda onde usuários podem adicionar suas roupas, criar looks, e participar de discussões sobre tendências e estilos. É um espaço para entusiastas da moda compartilharem suas criações e opiniões, além de interagirem com uma comunidade apaixonada por moda.

**Comment by RuanW01** [comment]
Ideia 5
Pagina web sobre aprendizado online, será uma plataforma inovadora dedicada ao intercâmbio de habilidades entre indivíduos. A ideia é criar uma comunidade onde pessoas podem oferecer suas habilidades em troca de aprender novas competências, promovendo o aprendizado mútuo e a colaboração.

**Comment by jose-gp21** [comment]
Ideia 5: Diário de Boas Ações, um sistema onde os usuários possam expor boas ações e promover o bem no mundo.

**Comment by jdecarli6** [comment]
ideia 7: 

Catálogo de Livros: Um aplicativo para registrar e organizar uma coleção de livros, com detalhes como título, autor e gênero.

**Comment by rafaellucasrockenbach** [comment]
Ideia 8
Integração de placa solar com celulares, seria basicamente um aplicativo ou site que pegaria os dados de sua placa solar e lhe mostrar os dados referentes aos ganhos etc, além de poder mandar a energia de sobra para outra rede de forma digital.

**Comment by RuanW01** [comment]
Ideia 9
Pagina web que crie uma comunidade de pessoas para auxiliarem na preservação do meio ambiente, será uma plataforma voltada para o engajamento comunitário em iniciativas ambientais e sustentabilidade. O objetivo é conectar indivíduos e grupos com projetos ecológicos, desafios sustentáveis e oportunidades de impacto positivo, facilitando a participação e a colaboração em ações ambientais.

**Comment by RuanW01** [comment]
Ideia 10
Pagina web que será como se fosse um hospital virtual, uma plataforma de saúde personalizada que combina inteligência artificial com recomendações personalizadas para ajudar os usuários a gerenciar seu bem-estar físico e mental de maneira integrada e personalizada. O site oferece planos de saúde personalizados, rastreamento de progresso e suporte comunitário, com foco na melhoria contínua e no engajamento saudável.

**Comment by RuanW01** [comment]
Ideia 11
Pagina web que professores e artistas possam criar novas ideias, será uma plataforma criativa que conecta artistas de diferentes disciplinas, como pintura, escultura, música e design, para colaborar em projetos artísticos multidisciplinares. A plataforma promove a colaboração entre artistas, facilita a co-criação de obras e organiza eventos de arte inovadores.

**Comment by jose-gp21** [comment]
Ideia 11:
Aplicativo de Mobilidade Urbana: Compartilhamento de carros que não estão em uso
